### PR TITLE
Fix websocket detection on firefox and add tests

### PR DESCRIPTION
**Pull request by jumanjiman**
~~Two~~ Three commits:
* add basic editorconfig
* update travis for current build requirements
* resolve https://github.com/nicolasazrak/caddy-cache/issues/18

### CODE REVIEW

**Comment by jumanjiman** [comment]
Notes about the travis failure:

* Build now requires go 1.12 (not 1.11 as in the travis cocnfig) due to module dependencies

* Travis failure at https://travis-ci.org/nicolasazrak/caddy-cache/builds/525002975#L490-L492 :

  ```
  package github.com/lucas-clemente/quic-go/h2quic: cannot find package "github.com/lucas-clemente/quic-go/h2quic" in any of:
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/github.com/lucas-clemente/quic-go/h2quic (from $GOROOT)
	/home/travis/gopath/src/github.com/lucas-clemente/quic-go/h2quic (from $GOPATH)
  ```

  ...can be resolved as described at https://github.com/caddyserver/forwardproxy/issues/54

**Comment by jumanjiman** [comment]
added a commit that updates travis to update golang version to new minimum version (1.12)

**Comment by nicolasazrak** [comment]
Thanks @jumanjiman !

**Comment by jumanjiman** [comment]
awesome, ty!

**Pull request merged**
