### PR TITLE
cache_key configuration

### PR DESCRIPTION
**Pull request by wyattjoh**
This PR serves to add support to caddy-cache for configuring the cache key used using Caddy [Placeholders](https://caddyserver.com/docs/placeholders).

### Ignore the query string

```
cache { cache_key "{method} {host}{path}" }
```

```
Request: GET https://example.com/test?some=variable
Cache Key: GET example.com/test
```

### Cache per user (via basic auth)

```
cache { cache_key "{method} {host}{path}?{query} {user}" }
```

```
Request: GET https://bob:my-password@example.com/test?some=variable
Cache Key: GET example.com/test?some=variable bob
```

## :rotating_light: Caveats :rotating_light:

**Note**: This may/may not  be an issue, but using placeholders, it's currently not possible to do conditional operations like you see here:

https://github.com/nicolasazrak/caddy-cache/blob/a00a842f2578bd6be07bc21f004c3312a107c0ab/handler.go#L49-L52

So instead, the default cache key reads: `{method} {host}{path}?{query}` which when for example, a request comes in as `GET https://example.com/test`, the cache key will be `GET example.com/test?` instead of the current `GET example.com/test`. This will result in entries that are invalidated, because of the additional `?`, but besides that, I think it's more flexible.

### CODE REVIEW

**Comment by nicolasazrak** [comment]
It looks good at first sight, I'm going to test it a little bit and look it deeper and merge it as soon as possible

**Comment by nicolasazrak** [comment]
@wyattjoh It definitely looks good, can you add a few tests so I can merge it?

**Comment by wyattjoh** [comment]
Added some tests @nicolasazrak! Let me know what you think!

**Comment by nicolasazrak** [comment]
@wyattjoh Nice work !

**Pull request merged**
